language: python

sudo: required

matrix:
  include:
      - os: linux
        python: 3.6
        services:
          - docker
        env:
          - PIP=pip
      - os: osx
        language: generic
        env:
          - PYVERSION='3.6.0'

install:
- export CIBW_SKIP="cp33-* cp34-* *i686"
- export CIBW_TEST_REQUIRES="pytest six numpy"
- export CIBW_TEST_COMMAND="pytest {project}/spiceypy/tests/*"
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew outdated | grep -q pyenv && brew upgrade pyenv || true; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then eval "$(pyenv init -)"; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then pyenv install $PYVERSION; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then pyenv global $PYVERSION; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then pyenv versions; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then python --version; fi
- pip install -U pip
- pip install -U wheel
- pip wheel numpy
- pip install numpy
- pip install twine
- pip install cibuildwheel==0.7.1

script:
- ls -lahtr
- ls -lahtr ./SpiceyPy/
- cd ./SpiceyPy/
- cibuildwheel --output-dir ./wheelhouse
- ls -lahtr /tmp/delocated_wheel/
- ls -lahtr /project/spiceypy/
- ls -lahtr /project/spiceypy/utils/
- ls -lahtr /project/spiceypy/
- ls -lahtr ./spiceypy/utils/
- ls -lahtr ./spiceypy/dist
- ls -lahtr ./
- ls ./wheelhouse/

after_success:
- ls -lahtr wheelhouse/
- unzip -l wheelhouse/*

