language: python

# The travis Python version is unrelated to the version we build and test
# with.  This is set with the MB_PYTHON_VERSION variable.
python: 3.5
sudo: required
dist: trusty
services: docker

matrix:
  include:
      - os: linux
          dist: trusty
          python: 3.6
          sudo: required
          services:
            - docker
          env:
            - PIP=pip
            - CIBW_SKIP="cp33-* cp34-* *i686"
      - os: osx
          language: generic
          env:
            - PYVERSION='3.6.0'
            - CIBW_SKIP="cp33-* cp34-* *i686"

before_install:
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew outdated | grep -q pyenv && brew upgrade pyenv || true; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then eval "$(pyenv init -)"; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then pyenv install $PYVERSION; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then pyenv global $PYVERSION; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then pyenv versions; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then python --version; fi
- pip install -U pip
- pip install -U wheel
- pip wheel numpy
- pip install numpy
- pip install twine
- pip install cibuildwheel==0.7.1

install:
- mv SpiceyPy/* ./
- cibuildwheel --output-dir wheelhouse

after_success:
- ls wheelhouse/
- unzip -l wheelhouse/*

